# Generated by Django 4.1.10 on 2023-10-24 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("complete_content", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ON_LOAN", "ON_LOAN"),
                            ("READY", "READY"),
                            ("SERVICING", "SERVICING"),
                            ("RETIRED", "RETIRED"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.JSONField()),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="kits.blueprint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("LOAN", "LOAN"), ("RESTOCK", "RESTOCK")],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("person", models.CharField(max_length=50)),
                ("pre_snapshot", models.JSONField()),
                ("post_snapshot", models.JSONField()),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="kits.kit"
                    ),
                ),
            ],
        ),
    ]
