version: 2
updates:
  - package-ecosystem: "npm" # For npm packages
    directory: "/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip" # For Python packages
    directory: "/backend"
    schedule:
      interval: "weekly"
