# docker-compose.yml

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
      target: development
    expose:
      - "5173"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: development
    expose:
      - "8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env 
