# docker-compose-prod.yml

services:
  frontend:
    platform: linux/amd64
    image: sjbdeck/deck-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - backend
      - certbot

  backend:
    platform: linux/amd64
    image: sjbdeck/deck-backend:latest
    env_file:
      - .env 
    expose:
      - "8000"
    environment:
      DB_USER: ${MYSQL_USER}
      DB_PW: ${MYSQL_PASSWORD}
      DB_HOST: mysql
    depends_on:
      - mysql
    command: >
      sh -c "
        ./wait-for-it.sh mysql:3306 -- 
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
  
  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 168h & wait $${!}; done;'"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: deck
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - deck_data:/var/lib/mysql

volumes:
  deck_data:
