# docker-compose.yml

services:

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: development
    ports:
      - "80:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env 
