# docker-compose-prod.yml

services:

  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./backend/static:/app/static
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: production
    env_file:
      - .env 
    expose:
      - "8000"
