ERRORS = "errors"
WARNINGS = "warnings"
INFO = "info"

BLUEPRINT = "blueprint"
KIT = "kit"
HISTORY = "history"

ON_LOAN = "ON_LOAN"
READY = "READY"
SERVICING = "SERVICING"
RETIRED = "RETIRED"

LOAN = "LOAN"
RESTOCK = "RESTOCK"
CREATION = "CREATION"
RETIREMENT = "RETIREMENT"

KIT_STATUS = [ON_LOAN, READY, SERVICING, RETIRED]
HISTORY_TYPE = [LOAN, RESTOCK, CREATION, RETIREMENT]
