# Generated by Django 4.1.6 on 2023-05-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userextras",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
