# Generated by Django 4.1.10 on 2023-07-23 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_userextras_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userextras",
            old_name="profilepic",
            new_name="profile_pic",
        ),
        migrations.AlterField(
            model_name="userextras",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extras",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
