# Generated by Django 4.1.6 on 2023-05-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Bandages", "Bandages"),
                            ("Solution", "Solution"),
                            ("Dressing", "Dressing"),
                            ("Universal Precaution", "Universal Precaution"),
                            ("General", "General"),
                        ],
                        default="General",
                        max_length=50,
                    ),
                ),
                ("unit", models.CharField(default="units", max_length=50)),
                ("image", models.CharField(blank=True, max_length=100, null=True)),
                ("total_quantityopen", models.IntegerField(default=0)),
                ("total_quantityunopened", models.IntegerField(default=0)),
                (
                    "min_quantityopen",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "min_quantityunopened",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
            ],
        ),
    ]
