# Generated by Django 4.1.10 on 2023-11-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="type",
            field=models.CharField(
                choices=[
                    ("LOAN", "LOAN"),
                    ("RESTOCK", "RESTOCK"),
                    ("CREATION", "CREATION"),
                    ("RETIREMENT", "RETIREMENT"),
                ],
                max_length=50,
            ),
        ),
    ]
