# Generated by Django 4.1.6 on 2023-06-02 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemExpiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expirydate", models.DateField(blank=True, null=True)),
                ("quantityopen", models.IntegerField(default=0)),
                ("quantityunopened", models.IntegerField(default=0)),
                ("archived", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expirydates",
                        to="inventory.item",
                    ),
                ),
            ],
        ),
    ]
