# Generated by Django 4.1.10 on 2023-12-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_history_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanhistory",
            name="return_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loanorder",
            name="due_date",
            field=models.DateField(),
        ),
    ]
