# Generated by Django 4.1.10 on 2023-08-30 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_loanorder_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="item_expiry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_ordered",
                to="inventory.itemexpiry",
            ),
        ),
    ]
