# Generated by Django 4.1.6 on 2023-06-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_itemexpiry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="image",
        ),
        migrations.AddField(
            model_name="item",
            name="profilepic",
            field=models.ImageField(blank=True, null=True, upload_to="item_img"),
        ),
    ]
