# Generated by Django 4.1.10 on 2023-10-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_blueprint_kit_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="blueprint",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "ACTIVE"), ("DELETED", "DELETED")],
                default="ACTIVE",
                max_length=50,
            ),
        ),
    ]
