# Generated by Django 4.1.10 on 2023-10-29 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_blueprint_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanHistory",
            fields=[
                (
                    "history_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="inventory.history",
                    ),
                ),
                ("loanee_name", models.CharField(max_length=50)),
                ("due_date", models.DateTimeField()),
                ("return_date", models.DateTimeField(blank=True, null=True)),
            ],
            bases=("inventory.history",),
        ),
        migrations.RenameField(
            model_name="history",
            old_name="post_snapshot",
            new_name="snapshot",
        ),
        migrations.RemoveField(
            model_name="history",
            name="pre_snapshot",
        ),
        migrations.AlterField(
            model_name="history",
            name="type",
            field=models.CharField(
                choices=[
                    ("LOAN", "LOAN"),
                    ("RETURN", "RETURN"),
                    ("RESTOCK", "RESTOCK"),
                    ("CREATION", "CREATION"),
                    ("RETIREMENT", "RETIREMENT"),
                    ("REVERT", "REVERT"),
                ],
                max_length=50,
            ),
        ),
    ]
