# Generated by Django 4.1.6 on 2023-07-11 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_order_orderitem_loanorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="item_expiry",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.DeleteModel(
            name="LoanOrder",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
