# Generated by Django 4.1.10 on 2023-07-22 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0006_alter_orderitem_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="min_quantityopen",
        ),
        migrations.RemoveField(
            model_name="item",
            name="min_quantityunopened",
        ),
        migrations.RemoveField(
            model_name="item",
            name="total_quantityopen",
        ),
        migrations.RemoveField(
            model_name="item",
            name="total_quantityunopened",
        ),
        migrations.RemoveField(
            model_name="itemexpiry",
            name="quantityopen",
        ),
        migrations.RemoveField(
            model_name="itemexpiry",
            name="quantityunopened",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="opened_quantity",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="unopened_quantity",
        ),
        migrations.AddField(
            model_name="item",
            name="is_opened",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="min_quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="total_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="itemexpiry",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
