# Generated by Django 4.1.10 on 2023-10-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0006_loanhistory_rename_post_snapshot_history_snapshot_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
