# Generated by Django 4.1.10 on 2023-10-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_alter_history_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="type",
            field=models.CharField(
                choices=[
                    ("LOAN", "LOAN"),
                    ("RETURN", "RETURN"),
                    ("RESTOCK", "RESTOCK"),
                    ("CREATION", "CREATION"),
                    ("RETIREMENT", "RETIREMENT"),
                    ("LOAN AND REVERT", "LOAN AND REVERT"),
                ],
                max_length=50,
            ),
        ),
    ]
