# Generated by Django 4.1.10 on 2023-07-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_order_orderitem_loanorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanorder",
            name="loan_active",
            field=models.BooleanField(default=True),
        ),
    ]
