# Generated by Django 4.1.10 on 2023-07-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_remove_item_min_quantityopen_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="quantity",
            new_name="ordered_quantity",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="returned_quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
