# Generated by Django 4.1.10 on 2023-07-14 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_loanorder_loan_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanorder",
            name="id",
        ),
        migrations.RemoveField(
            model_name="loanorder",
            name="order",
        ),
        migrations.AddField(
            model_name="loanorder",
            name="order_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="inventory.order",
            ),
            preserve_default=False,
        ),
    ]
