# Generated by Django 4.1.10 on 2023-10-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_alter_history_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blueprint",
            name="status",
        ),
        migrations.AddField(
            model_name="blueprint",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
