# Generated by Django 4.1.10 on 2023-07-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_rename_quantity_orderitem_ordered_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="returned_quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
