# Generated by Django 4.1.10 on 2023-11-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_remove_blueprint_status_blueprint_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="order_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="kit",
            name="content",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="reason",
            field=models.CharField(
                choices=[
                    ("kit_restock", "Kit Restock"),
                    ("kit_retire", "Kit Retire"),
                    ("loan", "Loan"),
                    ("unserviceable", "Unserviceable"),
                    ("others", "Others"),
                    ("item_restock", "Item Restock"),
                ],
                max_length=50,
            ),
        ),
    ]
