# Generated by Django 4.1.10 on 2023-07-23 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_alter_orderitem_returned_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemexpiry",
            old_name="expirydate",
            new_name="expiry_date",
        ),
        migrations.AlterField(
            model_name="itemexpiry",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expiry_dates",
                to="inventory.item",
            ),
        ),
    ]
