# Generated by Django 4.1.10 on 2023-07-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_rename_expirydate_itemexpiry_expiry_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanorder",
            name="return_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
