# Generated by Django 4.1.10 on 2023-11-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_history_order_id_alter_kit_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="reason",
            field=models.CharField(
                choices=[
                    ("kit_restock", "Kit Restock"),
                    ("kit_create", "Kit Create"),
                    ("kit_retire", "Kit Retire"),
                    ("loan", "Loan"),
                    ("unserviceable", "Unserviceable"),
                    ("others", "Others"),
                    ("item_restock", "Item Restock"),
                ],
                max_length=50,
            ),
        ),
    ]
