# Generated by Django 4.1.13 on 2024-05-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_itemexpiry_item_alter_order_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_reverted",
            field=models.BooleanField(default=False),
        ),
    ]
